import { useEffect, useState } from 'react'
import { apiClient } from '../../services/api/apiClient.js'
import { getCurrentCoordinates } from './geolocation.js'
import { PlaceAutocomplete } from './PlaceAutocomplete.jsx'
import { createTripRequest, defaultTripForm, validateTripForm } from './tripRequest.js'
import { getStoredTripForm, saveTripRequest } from './tripRequestStorage.js'

const stored = getStoredTripForm()
const toForm = (saved) => saved ? { ...defaultTripForm, ...saved, appointmentTime: saved.appointmentAt ? new Date(saved.appointmentAt).toTimeString().slice(0, 5) : '', withoutAppointment: !saved.appointmentAt, currentFloor: String(saved.currentFloor), heightCm: saved.heightCm ? String(saved.heightCm) : '' } : defaultTripForm
const hours = Array.from({ length: 24 }, (_, value) => String(value).padStart(2, '0'))
const minutes = Array.from({ length: 60 }, (_, value) => String(value).padStart(2, '0'))

export function TripRequestForm({ onComplete, onError, profile, isRegistered, mapSelection, onMapSelectionHandled, mapTarget, onMapTargetChange }) {
  const [values, setValues] = useState(() => toForm(stored))
  const [errors, setErrors] = useState({})
  const [locationStatus, setLocationStatus] = useState('')
  useEffect(() => { if (!mapSelection) return undefined; const timer = window.setTimeout(() => { setValues((current) => ({ ...current, [mapSelection.target]: mapSelection.place })); setLocationStatus(`${mapSelection.place.name}을(를) ${mapSelection.target === 'origin' ? '출발지' : '도착지'}로 지정했습니다.`); onMapSelectionHandled() }, 0); return () => window.clearTimeout(timer) }, [mapSelection, onMapSelectionHandled])
  const update = (event) => { const { name, value } = event.target; setValues((current) => ({ ...current, [name]: value })) }
  const setPlace = (key) => (place) => setValues((current) => ({ ...current, [key]: place }))
  const useCurrentLocation = async () => { try { setLocationStatus('현재 위치를 확인하는 중…'); const coordinates = await getCurrentCoordinates(); const place = await apiClient.reverseGeocode(coordinates); setPlace('origin')(place); setLocationStatus(`${place.name}을(를) 출발지로 선택했습니다.`) } catch (locationError) { setLocationStatus(locationError.message) } }
  const submit = (event) => { event.preventDefault(); const withProfileHeight = isRegistered && profile.heightCm ? { ...values, heightCm: String(profile.heightCm) } : values; const nextErrors = validateTripForm(withProfileHeight); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; try { saveTripRequest(createTripRequest(withProfileHeight)); onComplete() } catch (submitError) { onError(submitError) } }
  const pickSavedPlace = (place) => { if (place) setValues((current) => ({ ...current, [mapTarget === 'destination' ? 'destination' : 'origin']: place })) }
  return <form className="route-form" onSubmit={submit} noValidate><div className="location-tabs" role="group" aria-label="지도 선택 대상"><button className={mapTarget === 'origin' ? 'active' : ''} type="button" onClick={() => onMapTargetChange('origin')}>출발</button><button className={mapTarget === 'destination' ? 'active' : ''} type="button" onClick={() => onMapTargetChange('destination')}>도착</button></div>{(mapTarget === 'home' || mapTarget === 'work') && <p className="field-hint">지도에서 지점을 누른 뒤 {mapTarget === 'home' ? '집' : '회사'}으로 지정해 주세요.</p>}<div className="form-grid"><div><PlaceAutocomplete label="출발지" selected={values.origin} onSelect={setPlace('origin')} error={errors.origin} /><button className="text-button" type="button" onClick={useCurrentLocation}>현재 위치</button></div><PlaceAutocomplete label="도착지" selected={values.destination} onSelect={setPlace('destination')} error={errors.destination} /></div>{isRegistered && <section className="saved-place-row" aria-label="저장한 장소"><button type="button" onClick={() => pickSavedPlace(profile.home)} disabled={!profile.home}>⌂ 집 {mapTarget === 'destination' ? '으로' : '에서'}</button><button type="button" onClick={() => pickSavedPlace(profile.work)} disabled={!profile.work}>▣ 회사 {mapTarget === 'destination' ? '으로' : '에서'}</button><button type="button" onClick={() => onMapTargetChange('home')}>집 설정</button><button type="button" onClick={() => onMapTargetChange('work')}>회사 설정</button></section>}<AppointmentTimePicker value={values.appointmentTime} withoutAppointment={values.withoutAppointment} error={errors.appointmentTime} onChange={(appointmentTime) => setValues((current) => ({ ...current, appointmentTime }))} onToggle={(withoutAppointment) => setValues((current) => ({ ...current, withoutAppointment }))} /><div className="compact-fields"><label>현재 층<input name="currentFloor" type="number" value={values.currentFloor} onChange={update} /></label>{!isRegistered && <Field label="키 (cm)" name="heightCm" type="number" value={values.heightCm} error={errors.heightCm} onChange={update} />}</div>{errors.currentFloor && <span className="field-error" role="alert">{errors.currentFloor}</span>}{locationStatus && <p className="field-hint" role="status">{locationStatus}</p>}<div className="actions"><button className="button route-submit" type="submit">대중교통 길찾기</button></div></form>
}
function Field({ label, error, ...props }) { return <label>{label}<input {...props} />{error && <span className="field-error" role="alert">{error}</span>}</label> }
function AppointmentTimePicker({ value, withoutAppointment, error, onChange, onToggle }) { const [selectedHour = '', selectedMinute = ''] = value.split(':'); const setHour = (hour) => onChange(`${hour}:${selectedMinute || '00'}`); const setMinute = (minute) => onChange(`${selectedHour || '00'}:${minute}`); return <fieldset className="time-picker"><div className="time-picker-heading"><legend>약속 시간 (오늘)</legend><button className={`appointment-toggle${withoutAppointment ? ' active' : ''}`} type="button" aria-pressed={withoutAppointment} onClick={() => onToggle(!withoutAppointment)}>시간 없이 보기</button></div>{withoutAppointment ? <p className="field-hint">약속 시간 없이 현재 기준 예상 이동 시간만 보여드려요.</p> : <div className="time-selects"><label>시<select value={selectedHour} onChange={(event) => setHour(event.target.value)}><option value="">시</option>{hours.map((hour) => <option key={hour} value={hour}>{hour}시</option>)}</select></label><label>분<select value={selectedMinute} onChange={(event) => setMinute(event.target.value)}><option value="">분</option>{minutes.map((minute) => <option key={minute} value={minute}>{minute}분</option>)}</select></label></div>}{error && <span className="field-error" role="alert">{error}</span>}</fieldset> }
